apiVersion: v1
kind: Secret
metadata:
  name: campaign-secrets
  namespace: campaign-suite
type: Opaque
stringData:
  rabbitmq-user: admin
  rabbitmq-password: admin123
  grafana-user: admin
  grafana-password: admin123
